language: swift
xcode_project: LanguageAnalyzer.xcodeproj # path to your xcodeproj folder
xcode_scheme: LanguageAnalyzer
xcode_destination: platform:iOS Simulator, id:1CED7FFD-E495-4BFD-B866-8A0EB1844B03, OS:11.4, name:iPhone X 
